# Generated by Django 4.1 on 2022-09-04 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiao_shop', '0008_alter_xiaoshoprate_options_remove_xiaoshoprate_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeableCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_del', models.BooleanField(default=False)),
                ('cardnum', models.CharField(blank=True, default='', help_text='充值卡号', max_length=32, unique=True, verbose_name='订单号')),
                ('num', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='金额')),
                ('is_use', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '充值卡',
                'verbose_name_plural': '充值卡',
            },
        ),
    ]
